dist: releases
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'

builds:
  - id: default
    binary: makefat
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: g-linville
    name: makefat
  prerelease: auto